### ISSUE TITLE
Function of `auth0_rule_namespace`?

### ISSUE THREAD

**Issue by jtc42** [dorinclisu/fastapi-auth0#2]
Hey, thanks for working on this! The timing is amazing for me.

I've been trying to get to grips with the code for this module, and I'm just wondering what's the function of the `auth0_rule_namespace` constant? The only time it's used seems to be in the Auth0 user model, as an alias for `email`. Mostly for my own sanity I was wondering if you could clarify what this is for?

Thanks!

Joel

**Comment by dorinclisu** [comment]
Hi, you need to use this constant in the rule for obtaining email address, otherwise user.email will always be None (and deny authorization if email_auto_error = True in Auth0() constructor).

The requirement for a namespace is enforced by auth0 in order to clearly differentiate between standard and non-standard claims in an access token. Without a namespace, auth0 will silently ignore the rule. 

<img width="1010" alt="Screenshot 2021-03-01 at 18 03 17" src="https://user-images.githubusercontent.com/13818396/109524005-a70ab500-7ab8-11eb-86c7-be4d52a122e8.png">

**Comment by jtc42** [comment]
Oh I see! I got confused by the documentation. That's on me misreading it though. Thanks!
