### ISSUE TITLE
Get a lost of user roles?

### ISSUE THREAD

**Issue by emillykkejensen** [dorinclisu/fastapi-auth0#33]
Quite new to auth0 so really like your repo here. Is there any way to get all the roles, assigned to a user?

**Comment by dorinclisu** [comment]
Not possible to get role from the access token, because it's an anti-pattern to implement authorization by checking role names. 
Instead, auth0 roles contain sets of permissions, and the access token of the user contains the combined permissions of the roles assigned to the user.

Then the api endpoints implement checks for the specific permissions.
